// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSUM42pf54lG7wCCrTjUm6zUDjeKS4bZU',
    appId: '1:145088448850:web:ca0b612bae6c874236d28b',
    messagingSenderId: '145088448850',
    projectId: 'recipes-app-8513a',
    authDomain: 'recipes-app-8513a.firebaseapp.com',
    storageBucket: 'recipes-app-8513a.firebasestorage.app',
    measurementId: 'G-V0LS3QVVLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgm5seZzZAyEibNwOArKmXttlRWNbdInk',
    appId: '1:145088448850:android:29eb3a978422835536d28b',
    messagingSenderId: '145088448850',
    projectId: 'recipes-app-8513a',
    storageBucket: 'recipes-app-8513a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYUPMKjmvqqc9xAXs8dRzECaz1fsIZ8nE',
    appId: '1:145088448850:ios:e6172a33f98b159936d28b',
    messagingSenderId: '145088448850',
    projectId: 'recipes-app-8513a',
    storageBucket: 'recipes-app-8513a.firebasestorage.app',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYUPMKjmvqqc9xAXs8dRzECaz1fsIZ8nE',
    appId: '1:145088448850:ios:e6172a33f98b159936d28b',
    messagingSenderId: '145088448850',
    projectId: 'recipes-app-8513a',
    storageBucket: 'recipes-app-8513a.firebasestorage.app',
    iosBundleId: 'com.example.recipesApp',
  );

}